name: Android CI with Fastlane

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      # Step 3: Set up Ruby (Fastlane is a Ruby gem)
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      # Step 4: Install Bundler & Fastlane
      - name: Install Fastlane
        run: |
          gem install bundler
          gem install fastlane

      # Step 5: Run Fastlane test lane (unit tests)
      - name: Run Fastlane tests
        run: bundle exec fastlane android test

      # Step 6: Run Fastlane build lane (build APK)
      - name: Run Fastlane build
        run: bundle exec fastlane android beta

      # Step 7: Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release.apk
